export const mockForecast = [
	{
		name: "Overnight",
		temperature: 47,
		temperatureUnit: "F",
		probabilityOfPrecipitation: 30,
		windSpeed: "7 mph",
		windDirection: "W",
		shortForecast: "Chance Rain Showers",
		icon: "https://api.weather.gov/icons/land/night/rain_showers,30?size=medium",
	},
	{
		name: "Monday",
		temperature: 59,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "3 to 9 mph",
		windDirection: "WNW",
		shortForecast: "Mostly Sunny",
		icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
	},
	{
		name: "Tuesday",
		temperature: 61,
		temperatureUnit: "F",
		probabilityOfPrecipitation: 30,
		windSpeed: "7 to 13 mph",
		windDirection: "SW",
		shortForecast: "Chance Rain Showers then Partly Sunny",
		icon: "https://api.weather.gov/icons/land/day/rain_showers,30/bkn?size=medium",
	},
	{
		name: "Wednesday",
		temperature: 65,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "7 to 13 mph",
		windDirection: "NNW",
		shortForecast: "Sunny",
		icon: "https://api.weather.gov/icons/land/day/few?size=medium",
	},
	{
		name: "Thursday",
		temperature: 70,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "15 to 21 mph",
		windDirection: "NNE",
		shortForecast: "Sunny",
		icon: "https://api.weather.gov/icons/land/day/wind_skc?size=medium",
	},
	{
		name: "Friday",
		temperature: 71,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "10 mph",
		windDirection: "NNE",
		shortForecast: "Sunny",
		icon: "https://api.weather.gov/icons/land/day/few?size=medium",
	},
	{
		name: "Saturday",
		temperature: 69,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "5 to 10 mph",
		windDirection: "SSW",
		shortForecast: "Sunny",
		icon: "https://api.weather.gov/icons/land/day/few?size=medium",
	},
	{
		name: "Sunday",
		temperature: 68,
		temperatureUnit: "F",
		probabilityOfPrecipitation: null,
		windSpeed: "5 to 10 mph",
		windDirection: "SW",
		shortForecast: "Sunny",
		icon: "https://api.weather.gov/icons/land/day/few?size=medium",
	},
];
